version: "3.7"
services:
    flask_1:
        image: "jas06113/marvel_tmi_flask_img:latest"
        container_name: flask
        expose:
            - 5000
        restart: "unless-stopped"
    proxy:
        image: "jas06113/marvel_tmi_proxy:latest"
        container_name: nginx 
        ports:
            - "80:80"
        restart: "unless-stopped"
